--- #YAML:1.0
name:                Apache2-Tail
version:             0.02
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    CGI:                           0
    File::Tail:                    0
    mod_perl2:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
